"""
ZeroSite v8.0 PDF Export Service

Converts v7.5 FINAL / v8.0 dynamic HTML reports to professional PDF documents.
This service receives the actual generated HTML and converts it to PDF,
ensuring that user inputs, real market data, and v8.0 analysis are properly reflected.

Key Features:
- Uses actual generated HTML (not static templates)
- Preserves 60+ page formatting
- Includes all v8.0 market data
- LH submission quality output
"""

from typing import Optional
import logging
from pathlib import Path
from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration
import hashlib
from datetime import datetime

logger = logging.getLogger(__name__)


class PDFExportV8:
    """
    PDF Export Service for ZeroSite v8.0
    
    Converts dynamically generated v7.5 FINAL / v8.0 HTML reports to PDF.
    CRITICAL: This service uses the actual HTML generated by the report engine,
    not static templates, ensuring all user data and API results are reflected.
    """
    
    def __init__(self):
        """Initialize PDF export service"""
        self.font_config = FontConfiguration()
        logger.info("📄 PDF Export v8.0 initialized")
    
    def convert_html_to_pdf(
        self,
        html_content: str,
        output_path: str,
        metadata: Optional[dict] = None
    ) -> dict:
        """
        Convert dynamic HTML content to PDF
        
        Args:
            html_content: The actual HTML string generated by v7.5/v8.0 report engine
            output_path: Path where PDF will be saved
            metadata: Optional metadata dict with report info
        
        Returns:
            dict with status, output_path, file_size, etc.
        """
        try:
            logger.info(f"🔄 Converting v7.5/v8.0 HTML to PDF: {output_path}")
            
            # Log HTML size to verify it's the full report
            html_size_kb = len(html_content) / 1024
            logger.info(f"   HTML size: {html_size_kb:.1f} KB")
            
            if html_size_kb < 10:
                logger.warning(f"   ⚠️ HTML size very small ({html_size_kb:.1f} KB) - may be using static template!")
            
            # Verify HTML contains v7.5 FINAL markers
            v75_markers = [
                'v7.5 FINAL',
                'LH 2025',
                '36개월',
                'Phase 1',
                'Phase 4'
            ]
            
            found_markers = [m for m in v75_markers if m in html_content]
            logger.info(f"   Found v7.5 markers: {len(found_markers)}/{len(v75_markers)}")
            
            if len(found_markers) < 3:
                logger.warning(f"   ⚠️ Few v7.5 markers found - may be using old template!")
            
            # Create HTML object from string
            html_doc = HTML(string=html_content)
            
            # Get PDF optimization CSS
            pdf_css = CSS(string=self._get_v8_pdf_css())
            
            # Generate PDF
            html_doc.write_pdf(
                output_path,
                stylesheets=[pdf_css],
                font_config=self.font_config
            )
            
            # Verify PDF was created
            pdf_path = Path(output_path)
            if pdf_path.exists():
                file_size = pdf_path.stat().st_size
                file_size_mb = file_size / (1024 * 1024)
                
                logger.info(f"✅ PDF generated successfully: {file_size_mb:.2f} MB")
                
                # Calculate content hash for verification
                content_hash = hashlib.md5(html_content.encode()).hexdigest()[:8]
                
                return {
                    'success': True,
                    'output_path': str(pdf_path.absolute()),
                    'file_size_mb': file_size_mb,
                    'html_size_kb': html_size_kb,
                    'content_hash': content_hash,
                    'v75_markers_found': len(found_markers),
                    'timestamp': datetime.now().isoformat(),
                    'metadata': metadata or {}
                }
            else:
                logger.error("❌ PDF file not created")
                return {
                    'success': False,
                    'error': 'PDF file not created'
                }
                
        except Exception as e:
            logger.error(f"❌ Error converting HTML to PDF: {str(e)}")
            return {
                'success': False,
                'error': str(e)
            }
    
    def convert_v75_report_to_pdf(
        self,
        report_response: dict,
        output_path: str
    ) -> dict:
        """
        Convert v7.5 FINAL report response to PDF
        
        Args:
            report_response: The response dict from LHReportGeneratorV75Final.run()
                            Must contain 'html' and 'metadata' fields
            output_path: Path where PDF will be saved
        
        Returns:
            dict with conversion status and info
        """
        if not report_response.get('success'):
            return {
                'success': False,
                'error': 'Report generation failed'
            }
        
        html_content = report_response.get('html')
        if not html_content:
            return {
                'success': False,
                'error': 'No HTML content in report response'
            }
        
        metadata = report_response.get('metadata', {})
        
        logger.info(f"📄 Converting v7.5 FINAL report to PDF")
        logger.info(f"   Report version: {metadata.get('version', 'unknown')}")
        logger.info(f"   Pages: {metadata.get('pages', 'unknown')}")
        logger.info(f"   Recommendation: {metadata.get('recommendation', 'unknown')}")
        
        return self.convert_html_to_pdf(html_content, output_path, metadata)
    
    def _get_v8_pdf_css(self) -> str:
        """
        v8.0 PDF optimization CSS
        
        Returns:
            CSS string optimized for 60+ page v7.5 FINAL reports
        """
        return """
        /* ZeroSite v8.0 PDF Optimization CSS */
        
        @page {
            size: A4 portrait;
            margin: 25mm 20mm 30mm 20mm;
            
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages);
                font-family: 'Noto Sans KR', 'Malgun Gothic', sans-serif;
                font-size: 9pt;
                color: #666;
            }
            
            @bottom-left {
                content: "ZeroSite v8.0 Professional Report";
                font-family: 'Noto Sans KR', 'Malgun Gothic', sans-serif;
                font-size: 9pt;
                color: #999;
            }
        }
        
        @page :first {
            margin: 0;
            
            @bottom-right {
                content: none;
            }
            
            @bottom-left {
                content: none;
            }
        }
        
        /* Ensure proper page breaks */
        .page-break {
            page-break-after: always;
            break-after: page;
        }
        
        .page-break-before {
            page-break-before: always;
            break-before: page;
        }
        
        .avoid-break,
        .report-section {
            page-break-inside: avoid;
            break-inside: avoid;
        }
        
        /* Optimize tables for PDF */
        table {
            page-break-inside: avoid;
            border-collapse: collapse;
            width: 100%;
        }
        
        thead {
            display: table-header-group;
        }
        
        tfoot {
            display: table-footer-group;
        }
        
        tr {
            page-break-inside: avoid;
        }
        
        /* Optimize images */
        img {
            max-width: 100%;
            height: auto;
            page-break-inside: avoid;
        }
        
        /* Better typography for print */
        body {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            font-family: 'Noto Sans KR', 'Malgun Gothic', sans-serif;
            line-height: 1.6;
            color: #333;
        }
        
        h1, h2, h3, h4, h5, h6 {
            page-break-after: avoid;
            page-break-inside: avoid;
            font-family: 'Noto Sans KR', 'Malgun Gothic', sans-serif;
        }
        
        /* Ensure lists don't break awkwardly */
        ul, ol {
            page-break-inside: avoid;
        }
        
        li {
            page-break-inside: avoid;
        }
        
        /* Links visible in print */
        a {
            color: #0047AB;
            text-decoration: none;
        }
        
        a[href^="http"]:after {
            content: " (" attr(href) ")";
            font-size: 0.8em;
            color: #666;
        }
        
        /* Hide screen-only elements */
        .no-print,
        button,
        .btn {
            display: none !important;
        }
        
        /* Optimize charts and graphs */
        .chart-container,
        .graph-container {
            page-break-inside: avoid;
            max-height: 250mm;
        }
        
        /* Better rendering for data tables */
        .data-table {
            font-size: 10pt;
        }
        
        .data-table th {
            background-color: #f0f0f0;
            font-weight: bold;
            padding: 8px;
            border: 1px solid #ddd;
        }
        
        .data-table td {
            padding: 6px 8px;
            border: 1px solid #ddd;
        }
        
        /* Financial data highlighting */
        .financial-highlight {
            background-color: #fff9e6;
            padding: 10px;
            border-left: 4px solid #f39c12;
            page-break-inside: avoid;
        }
        
        /* Risk warnings */
        .risk-warning {
            background-color: #ffe6e6;
            padding: 10px;
            border-left: 4px solid #e74c3c;
            page-break-inside: avoid;
        }
        
        /* Recommendations */
        .recommendation {
            background-color: #e6f7ff;
            padding: 10px;
            border-left: 4px solid #3498db;
            page-break-inside: avoid;
        }
        """


# Convenience function for quick PDF export
def export_v75_report_to_pdf(
    report_html: str,
    output_path: str,
    metadata: Optional[dict] = None
) -> dict:
    """
    Quick export function for v7.5 FINAL reports
    
    Args:
        report_html: The HTML content from v7.5 generator
        output_path: Where to save the PDF
        metadata: Optional metadata dict
    
    Returns:
        dict with conversion status
    """
    exporter = PDFExportV8()
    return exporter.convert_html_to_pdf(report_html, output_path, metadata)


def export_v75_response_to_pdf(
    report_response: dict,
    output_path: str
) -> dict:
    """
    Quick export function for v7.5 FINAL response object
    
    Args:
        report_response: Response from LHReportGeneratorV75Final.run()
        output_path: Where to save the PDF
    
    Returns:
        dict with conversion status
    """
    exporter = PDFExportV8()
    return exporter.convert_v75_report_to_pdf(report_response, output_path)
