#!/bin/bash
#
# ZeroSite v3.0.0 - Daily Metrics Report Generator
# Generates a comprehensive daily metrics report
#

API_URL="http://localhost:8091"
REPORT_DIR="/home/user/webapp/logs/daily_reports"
DATE=$(date '+%Y-%m-%d')
REPORT_FILE="$REPORT_DIR/daily_report_$DATE.md"

# Create report directory
mkdir -p "$REPORT_DIR"

# Function to get metrics
get_metrics() {
    curl -s "$API_URL/metrics" 2>/dev/null || echo "{}"
}

# Function to get health status
get_health() {
    curl -s "$API_URL/health" 2>/dev/null || echo "{}"
}

# Function to count reports
count_reports() {
    ls -1 /home/user/webapp/generated_reports/v3_report_*.html 2>/dev/null | wc -l
}

# Generate report
generate_daily_report() {
    local metrics=$(get_metrics)
    local health=$(get_health)
    local report_count=$(count_reports)
    
    # Parse JSON (using jq if available, otherwise basic parsing)
    if command -v jq &> /dev/null; then
        total_requests=$(echo "$metrics" | jq -r '.total_requests // 0')
        successful=$(echo "$metrics" | jq -r '.successful_requests // 0')
        failed=$(echo "$metrics" | jq -r '.failed_requests // 0')
        success_rate=$(echo "$metrics" | jq -r '.success_rate // 0')
        avg_time=$(echo "$metrics" | jq -r '.average_generation_time // 0')
        
        health_status=$(echo "$health" | jq -r '.status // "unknown"')
        uptime=$(echo "$health" | jq -r '.uptime_seconds // 0')
    else
        total_requests=0
        successful=0
        failed=0
        success_rate=0
        avg_time=0
        health_status="unknown"
        uptime=0
    fi
    
    # Calculate uptime percentage
    uptime_hours=$(echo "scale=2; $uptime / 3600" | bc 2>/dev/null || echo "0")
    
    # Get system stats
    disk_usage=$(df -h /home/user/webapp | awk 'NR==2 {print $5}')
    mem_usage=$(free -m | awk 'NR==2 {printf "%.1f%%", $3*100/$2}')
    
    # Generate report
    cat > "$REPORT_FILE" << EOF
# 📊 ZeroSite v3.0.0 - Daily Report

**Date**: $DATE  
**Generated**: $(date '+%Y-%m-%d %H:%M:%S')  
**System**: Production

---

## 🎯 Summary

| Metric | Value | Status |
|--------|-------|--------|
| Health Status | $health_status | $([ "$health_status" = "healthy" ] && echo "✅" || echo "⚠️") |
| Uptime | ${uptime_hours}h | $([ "${uptime_hours%.*}" -gt 20 ] && echo "✅" || echo "🔄") |
| Total Requests | $total_requests | 📊 |
| Success Rate | ${success_rate}% | $([ "${success_rate%.*}" -gt 95 ] && echo "✅" || echo "⚠️") |
| Avg Generation Time | ${avg_time}s | $(awk -v time="$avg_time" 'BEGIN{print (time < 2) ? "✅" : "⚠️"}') |

---

## 📈 Detailed Metrics

### Request Statistics
- **Total Requests**: $total_requests
- **Successful**: $successful
- **Failed**: $failed
- **Success Rate**: ${success_rate}%

### Performance
- **Average Generation Time**: ${avg_time}s
- **Uptime**: ${uptime_hours} hours
- **Reports Generated Today**: $report_count

### System Resources
- **Disk Usage**: $disk_usage
- **Memory Usage**: $mem_usage

---

## 🎯 Daily Highlights

### Achievements
- System operational for ${uptime_hours} hours
- Generated $report_count reports
- Maintained ${success_rate}% success rate

### Observations
$(if [ "$failed" -gt 0 ]; then
    echo "- ⚠️  $failed failed requests detected - review logs"
else
    echo "- ✅ Zero failed requests"
fi)

$(if awk -v time="$avg_time" 'BEGIN{exit !(time > 2)}'; then
    echo "- ⚠️  Average generation time ($avg_time s) exceeds 2s target"
else
    echo "- ✅ Performance within target (<2s)"
fi)

---

## 📊 Trend Analysis

### Compared to Yesterday
[Requires historical data - to be implemented]

---

## 🚨 Issues & Alerts

$(if [ "$failed" -gt 0 ] || [ "$health_status" != "healthy" ]; then
    echo "**Active Issues**:"
    [ "$health_status" != "healthy" ] && echo "- Health status: $health_status"
    [ "$failed" -gt 0 ] && echo "- Failed requests: $failed"
else
    echo "**No issues detected** ✅"
fi)

---

## 🎯 Action Items for Tomorrow

- [ ] Review logs if any failures
- [ ] Monitor performance trends
- [ ] Collect user feedback
- [ ] Update Week 1 Dashboard

---

## 🔗 Quick Access

- **Health Check**: $API_URL/health
- **Metrics**: $API_URL/metrics
- **API Docs**: $API_URL/docs

---

**Report Generated By**: daily_report.sh  
**Next Report**: $(date -d "+1 day" '+%Y-%m-%d')
EOF

    echo "✅ Daily report generated: $REPORT_FILE"
    
    # Display report
    cat "$REPORT_FILE"
}

# Main execution
echo "📊 Generating Daily Metrics Report..."
echo ""

generate_daily_report

# Optionally send email or notification
# mail -s "ZeroSite Daily Report - $DATE" admin@example.com < "$REPORT_FILE"

echo ""
echo "📧 To send via email, configure mail command and uncomment the mail line"
echo "📁 Report saved to: $REPORT_FILE"
