/**
 * M4 Schematic Viewer Component
 * ==============================
 * 
 * Displays 4 types of building schematics generated by M4 V2
 * 
 * Schematic Types:
 * 1. Ground Layout (지상 배치도)
 * 2. Standard Floor Plan (기준층 평면도)
 * 3. Basement Parking (지하주차 평면도)
 * 4. Massing Comparison (매스 비교)
 * 
 * Author: ZeroSite Frontend Team
 * Date: 2025-12-17
 */

import React, { useState } from 'react';
import './SchematicViewer.css';

export interface SchematicFiles {
  groundLayout: string;
  standardFloor: string;
  basementParking: string;
  massingComparison: string;
}

export interface SchematicViewerProps {
  parcelId: string;
  schematics: SchematicFiles;
  available?: boolean;
}

const TABS = [
  { id: 'ground', label: '지상 배치도', icon: '🏗️' },
  { id: 'floor', label: '기준층 평면도', icon: '📐' },
  { id: 'parking', label: '지하주차 평면도', icon: '🅿️' },
  { id: 'massing', label: '매스 비교', icon: '📊' },
];

export const SchematicViewer: React.FC<SchematicViewerProps> = ({
  parcelId,
  schematics,
  available = true,
}) => {
  const [activeTab, setActiveTab] = useState('ground');

  if (!available) {
    return (
      <div className="schematic-viewer-unavailable">
        <div className="unavailable-icon">📋</div>
        <h3>도면 생성 전</h3>
        <p>M4 분석이 완료되면 자동으로 4가지 도면이 생성됩니다.</p>
      </div>
    );
  }

  const getSchematicUrl = () => {
    switch (activeTab) {
      case 'ground':
        return schematics.groundLayout;
      case 'floor':
        return schematics.standardFloor;
      case 'parking':
        return schematics.basementParking;
      case 'massing':
        return schematics.massingComparison;
      default:
        return '';
    }
  };

  const currentTab = TABS.find((t) => t.id === activeTab);
  const schematicUrl = getSchematicUrl();
  const isPng = activeTab === 'massing';

  return (
    <div className="schematic-viewer">
      <div className="schematic-header">
        <h2 className="schematic-title">
          건축 도면
          <span className="parcel-id">필지 ID: {parcelId}</span>
        </h2>
      </div>

      {/* Tab Navigation */}
      <div className="schematic-tabs">
        {TABS.map((tab) => (
          <button
            key={tab.id}
            className={`tab-btn ${activeTab === tab.id ? 'active' : ''}`}
            onClick={() => setActiveTab(tab.id)}
          >
            <span className="tab-icon">{tab.icon}</span>
            <span className="tab-label">{tab.label}</span>
          </button>
        ))}
      </div>

      {/* Schematic Display */}
      <div className="schematic-content">
        <div className="schematic-display">
          {isPng ? (
            <img
              src={schematicUrl}
              alt={currentTab?.label}
              className="schematic-image"
            />
          ) : (
            <object
              data={schematicUrl}
              type="image/svg+xml"
              className="schematic-svg"
            >
              <p>도면을 불러올 수 없습니다.</p>
            </object>
          )}
        </div>

        <div className="schematic-info">
          <h3 className="info-title">{currentTab?.label}</h3>
          <p className="info-description">{getDescription(activeTab)}</p>
        </div>
      </div>

      {/* Download Buttons */}
      <div className="schematic-actions">
        <a
          href={schematicUrl}
          download
          className="btn-download"
        >
          <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
            <path
              d="M10 13L6 9L7.41 7.59L9 9.17V3H11V9.17L12.59 7.59L14 9L10 13Z"
              fill="currentColor"
            />
            <path
              d="M17 15V17H3V15H1V17C1 18.1 1.9 19 3 19H17C18.1 19 19 18.1 19 17V15H17Z"
              fill="currentColor"
            />
          </svg>
          현재 도면 다운로드
        </a>

        <button className="btn-download-all" onClick={() => downloadAll(schematics)}>
          <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
            <path
              d="M15 9H11V3H9V9H5L10 14L15 9Z"
              fill="currentColor"
            />
            <path
              d="M17 15V17H3V15H1V17C1 18.1 1.9 19 3 19H17C18.1 19 19 18.1 19 17V15H17Z"
              fill="currentColor"
            />
          </svg>
          전체 도면 다운로드 (ZIP)
        </button>
      </div>
    </div>
  );
};

// Helper functions
function getDescription(tabId: string): string {
  const descriptions = {
    ground:
      '대지 경계와 건물 배치를 보여주는 도면입니다. 건폐율, 주차 출입구 위치 등을 확인할 수 있습니다.',
    floor:
      '기준층(표준층) 평면도입니다. 세대 배치, 코어 위치, 전용/공용 면적 구성을 확인할 수 있습니다.',
    parking:
      '지하주차장 평면도입니다. 주차 대수, 램프 위치, 구조 기둥 배치를 확인할 수 있습니다.',
    massing:
      '대안별 건물 매싱 비교 도면입니다. 용적률 최대화(A안)와 주차 우선(B안)을 비교할 수 있습니다.',
  };
  return descriptions[tabId as keyof typeof descriptions] || '';
}

async function downloadAll(schematics: SchematicFiles) {
  // Simplified: Download each file individually
  // In production, create a ZIP file
  const files = [
    { name: 'ground_layout.svg', url: schematics.groundLayout },
    { name: 'standard_floor.svg', url: schematics.standardFloor },
    { name: 'basement_parking.svg', url: schematics.basementParking },
    { name: 'massing_comparison.png', url: schematics.massingComparison },
  ];

  for (const file of files) {
    const link = document.createElement('a');
    link.href = file.url;
    link.download = file.name;
    link.click();
    await new Promise((r) => setTimeout(r, 100));
  }

  alert('모든 도면 다운로드가 시작되었습니다!');
}

export default SchematicViewer;
